
EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/osd-merkur \
osd/er-rest-example-merkurboard/osd-merkur \
osd/rpl-border-router/osd-merkur \
osd/slip-radio/osd-merkur \
osd/arduino-dooralert/osd-merkur \
osd/arduino-merkurboard/osd-merkur \
osd/arduino-plantobserving/osd-merkur \
osd/arduino-roomalert/osd-merkur \
osd/arduino-sketch/osd-merkur \
osd/arduino-wateralert/osd-merkur \
osd/climate/osd-merkur \
osd/climate2/osd-merkur \
osd/servo-sensor/osd-merkur \
osd/pingtheplug/osd-merkur \
osd/powerbox/osd-merkur \
osd/embedd-vm-merkurboard/osd-merkur \
osd/light-actor/osd-merkur \
#osd/dual-rgbw-actor/osd-merkur \
#osd/light-shutter-control/osd-merkur \
#osd/pir-sensor/osd-merkur \
#osd/pwm-example/osd-merkur \
#osd/wallclock-timer/osd-merkur

TOOLS=

include ../Makefile.compile-test
