
EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/osd-merkur-128                     \
osd/er-rest-example-merkurboard/osd-merkur-128 \
osd/rpl-border-router/osd-merkur-128           \
osd/slip-radio/osd-merkur-128                  \
osd/arduino-dooralert/osd-merkur-128           \
osd/arduino-merkurboard/osd-merkur-128         \
osd/arduino-plantobserving/osd-merkur-128      \
osd/arduino-roomalert/osd-merkur-128           \
osd/arduino-sketch/osd-merkur-128              \
osd/arduino-wateralert/osd-merkur-128          \
osd/climate/osd-merkur-128                     \
osd/climate2/osd-merkur-128                    \
osd/servo-sensor/osd-merkur-128                \
osd/pingtheplug/osd-merkur-128                 \
osd/powerbox/osd-merkur-128                    \
osd/embedd-vm-merkurboard/osd-merkur-128       \
osd/light-actor/osd-merkur-128                 \
hello-world/osd-merkur-256                     \
osd/er-rest-example-merkurboard/osd-merkur-256 \
osd/rpl-border-router/osd-merkur-256           \
osd/slip-radio/osd-merkur-256                  \
osd/arduino-dooralert/osd-merkur-256           \
osd/arduino-merkurboard/osd-merkur-256         \
osd/arduino-plantobserving/osd-merkur-256      \
osd/arduino-roomalert/osd-merkur-256           \
osd/arduino-sketch/osd-merkur-256              \
osd/arduino-wateralert/osd-merkur-256          \
osd/climate/osd-merkur-256                     \
osd/climate2/osd-merkur-256                    \
osd/servo-sensor/osd-merkur-256                \
osd/pingtheplug/osd-merkur-256                 \
osd/powerbox/osd-merkur-256                    \
osd/embedd-vm-merkurboard/osd-merkur-256       \
osd/light-actor/osd-merkur-256                 \

#osd/dual-rgbw-actor/osd-merkur-128             \
#osd/light-shutter-control/osd-merkur-128       \
#osd/pir-sensor/osd-merkur-128                  \
#osd/pwm-example/osd-merkur-128                 \
#osd/wallclock-timer/osd-merkur-128             \

#osd/dual-rgbw-actor/osd-merkur-256             \
#osd/light-shutter-control/osd-merkur-256       \
#osd/pir-sensor/osd-merkur-256                  \
#osd/pwm-example/osd-merkur-256                 \
#osd/wallclock-timer/osd-merkur-256             \

TOOLS=

include ../Makefile.compile-test
